// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuAC3phA5rAv5k9vXhGRoMyuEbciMhc9Q',
    appId: '1:746901003370:web:9172d56abc929fafc7be13',
    messagingSenderId: '746901003370',
    projectId: 'cs-ia-db',
    authDomain: 'cs-ia-db.firebaseapp.com',
    storageBucket: 'cs-ia-db.appspot.com',
    measurementId: 'G-6YNREH1516',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJ1fWKjtZaJYBqpN1fmMjEPSDkBKt8LQ',
    appId: '1:746901003370:android:22ab97a24fd4403fc7be13',
    messagingSenderId: '746901003370',
    projectId: 'cs-ia-db',
    storageBucket: 'cs-ia-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVKW8bpSRvQRT0e_6ony0wOiPrXYn9i00',
    appId: '1:746901003370:ios:6dd00adb4c875764c7be13',
    messagingSenderId: '746901003370',
    projectId: 'cs-ia-db',
    storageBucket: 'cs-ia-db.appspot.com',
    iosClientId: '746901003370-mhdg17vv5bcna9rmulg9hgufu5818499.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondEye',
  );
}
